registries:
  - name: full-stacks
    url: full-stacks.dev:5000

clusters:
  - name: zhaokun
    stack_id: easetest-default-zhaokun
    endpoint: es.zhaokun.org:18080


tasks:
  - name: build_image
    type: BuildTask
    ignore_on_error: false
    image_tag: "{{codepush.repository_full_name}}:{{codepush.commit_id}}"
    dockerfile: rootfs/Dockerfile
    post_process:
      - eval: '{{set_context(codepush.repository_name+"_1",task.image_tag)}}'
  - name: publish_image
    type: PublishTask
    ignore_on_error: false
    image_tag: '{{get_context(codepush.repository_name+"_1")}}'
    registry: full-stacks
    post_process:
      - eval: '{{set_context(codepush.repository_name + "_1",task.registry.url+"/"+task.image_tag)}}'
  - name: deploy_with_easestack
    type: DeployTask
    ignore_on_error: false
    cluster: zhaokun
    image_tag: '{{get_context(codepush.repository_name+"_1")}}'
    component: test-server
  - name: update_configuration
    type: ConfigUpdateTask
    cluster: zhaokun
    configs:
      - component: test-server
        items:
          - file: test.yml
            map_to_file: /config-volume/test-123.yml
            is_sub_path: "false"

notifications:
  emails:
  - zhaokun@megaease.com

